services:
  angular-frontend:
    container_name: angular_frontend
    image: angular_frontend
    build:
      context: AngularFrontend
    ports:
      - "8080:80"
    environment:
      - WEB_API_URL=http://web_api

  web-api:
    container_name: web_api
    image: web_api
    build:
      context: WebAPI
    ports:
      - "8080"
    environment:
      - RABBIT_URL=amqp://rabbitmq
      - ConnectionStrings_PostgreSQL=TODO
    depends_on:
      - rabbitmq

  functions-worker:
    container_name: functions_worker
    image: functions_worker
    build:
      context: FunctionsWorker
    environment:
      - RABBIT_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
      - postgres

  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbitmq
    user: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics -q check_running
      interval: 5s
      timeout: 30s
      retries: 10

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: verySecurePassword123


volumes:
  postgres-data:
  rabbitmq-data:
  azurite-data:
