@BaseUrl = http://localhost:8080
@CounterId = foo-bar

### Retrieve counter by name
GET {{BaseUrl}}/counter/{{CounterId}}
Content-Type: application/json
Accept: application/json

### Increment counter by name
POST {{BaseUrl}}/counter/{{CounterId}}/increment
Content-Type: application/json
Accept: application/json

5
